import React from 'react';
import { MainLayout } from '@/components/main-layout';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

const TermsAndConditionsPage = () => {
  return (
    <MainLayout>
      {/* Main container with pitch black background and padding */}
      <div className="bg-background min-h-screen w-full py-24 px-4 sm:px-6 lg:px-8 flex flex-col items-center">

        {/* Back to Home Button */}
        <div className="w-full max-w-4xl mb-8">
          <Link href="/roadmap" passHref>
            <Button 
              className="btn-premium bg-primary/10 backdrop-blur-sm border border-primary/20 hover:border-primary/40 text-primary-foreground"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </Link>
        </div>

        {/* Glassmorphism Card */}
        <div className="w-full max-w-4xl bg-white/5 backdrop-blur-lg p-8 md:p-12 rounded-2xl border border-white/10 shadow-2xl shadow-primary/10">
          <h1 className="text-3xl font-bold text-gray-100 mb-4">Terms and Conditions for PathShala AI</h1>
          <p className="text-sm text-gray-400 mb-8">Last Updated: September 21, 2025</p>

          {/* Prose classes for dark mode styling */}
          <div className="prose prose-lg prose-invert text-gray-300 max-w-none">
            <h2>1. Agreement to Terms</h2>
            <p>By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.</p>

            <h2>2. User Accounts</h2>
            <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password. You agree to provide us with accurate, complete, and current information upon registration.</p>

            <h2>3. Use of Services</h2>
            <p>You agree not to use the Service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts.</p>

            <h2>4. AI-Generated Content</h2>
            <p>The career roadmaps, suggestions, quiz content, and other materials generated by our AI are for informational and guidance purposes only. We do not guarantee the accuracy, completeness, or suitability of any AI-generated content. You are solely responsible for the use and interpretation of this information.</p>

            <h2>5. Subscriptions and Payments</h2>
            <p>Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring basis. All payments are non-refundable.</p>

            <h2>6. Limitation of Liability</h2>
            <p>In no event shall PathShala AI, nor its directors or employees, be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of, or inability to access or use, the Service.</p>

            <h2>7. Governing Law</h2>
            <p>These Terms shall be governed in accordance with the laws of India, without regard to its conflict of law provisions.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at primusvlog@gmail.com</p>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default TermsAndConditionsPage;